spring:
  application:
    name: course-service
  datasource:
    url: jdbc:mysql://localhost:3306/edupage?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "@Mamoudou123"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

server:
  port: 8082
  servlet:
    context-path: /api

app:
  jwt:
    secret: MyVerySecureSecretKeyForAuthenticationJWTTokens2024WithEnoughCharacters
    expiration: 86400000

cxf:
  path: /ws
  servlet:
    init:
      service-list-path: /info

logging:
  level:
    com.nexis.course_service: DEBUG
    org.springframework.web: INFO
    org.apache.cxf: INFO
    io.jsonwebtoken: DEBUG
